export const testimonials = [
  {
    id: 7,
    name: "Priya Sharma",
    location: "Mumbai, India",
    date: "March 15, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Moisturizing & Soothing Body Lotion",
    text: "As someone with dry skin in Mumbai's humid weather, this lotion is a godsend! The rose fragrance is divine and it absorbs instantly without greasiness. My skin stays moisturized all day even in AC offices.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 8,
    name: "Rahul Kapoor",
    location: "Delhi, India",
    date: "April 2, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Radiance-Boosting Face Scrub",
    text: "Never thought I'd use a face scrub until my wife made me try this. The almond bits give perfect exfoliation - not too harsh like other scrubs. My dull office-worker skin actually glows now!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 4,
  },
  {
    id: 9,
    name: "Ananya Patel",
    location: "Ahmedabad, India",
    date: "February 28, 2025",
    image: "/beauty-skin.png",
    product: "Both Products",
    text: "The body lotion healed my cracked heels in a week! And the face scrub cleared my monsoon breakouts gently. As a dermatologist, I appreciate the clean ingredients. Now recommended to all my patients.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 10,
    name: "Vikram Singh",
    location: "Bangalore, India",
    date: "May 20, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Moisturizing & Soothing Body Lotion",
    text: "Perfect for post-gym shower! Doesn't sting freshly shaved skin and keeps dryness away despite daily workouts. The 200ml bottle lasts surprisingly long - great value.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 11,
    name: "Neha Reddy",
    location: "Hyderabad, India",
    date: "June 10, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Radiance-Boosting Face Scrub",
    text: "My grandmother's ubtan recipe in a modern form! The lentil powder gives such natural brightness. Even my sensitive skin handles it well 2-3 times weekly. Packaging is travel-friendly too.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 12,
    name: "Arjun Mehta",
    location: "Pune, India",
    date: "July 5, 2025",
    image: "/beauty-skin.png",
    product: "Both Products",
    text: "The lotion saved my skin after years of chemical-laden products. Combined with the scrub, my dark elbows and knees have lightened noticeably in 6 weeks. Worth every rupee!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 13,
    name: "Divya Iyer",
    location: "Chennai, India",
    date: "January 18, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Moisturizing & Soothing Body Lotion",
    text: "Living in Chennai's heat, most lotions make me sweat. This one hydrates without clogging pores! The aloe vera soothes my skin after threading sessions. My holy grail product.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 14,
    name: "Rohit Verma",
    location: "Kolkata, India",
    date: "April 30, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Radiance-Boosting Face Scrub",
    text: "The rice powder exfoliates so gently yet effectively! My beard area stays bump-free since using this. No more expensive salon facials needed.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 4,
  },
  {
    id: 15,
    name: "Sunita Joshi",
    location: "Jaipur, India",
    date: "March 8, 2025",
    image: "/beauty-skin.png",
    product: "Both Products",
    text: "At 52, these products give me better results than luxury brands. The scrub removes my makeup completely while the lotion keeps my mature skin plump. The rose scent is nostalgic of my childhood.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 16,
    name: "Aditya Malhotra",
    location: "Chandigarh, India",
    date: "May 15, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Moisturizing & Soothing Body Lotion",
    text: "Perfect for North Indian winters! Healed my wind-chapped skin in days. The almond oil content makes it nourishing without being heavy. My whole family uses it now.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },

  // US TESTIMONIALS (10)
  {
    id: 17,
    name: "Emily Johnson",
    location: "New York, USA",
    date: "June 3, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Radiance-Boosting Face Scrub",
    text: "This replaced my $50 exfoliator! The coconut shreds give the perfect texture - not too abrasive. My makeup goes on smoother than ever. Obsessed with the natural ingredients list!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 18,
    name: "Michael Rodriguez",
    location: "Los Angeles, USA",
    date: "July 12, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Moisturizing & Soothing Body Lotion",
    text: "As a surfer, my skin takes a beating from sun and saltwater. This lotion heals my skin overnight! The vitamin E really works. No more ashy skin even after hours in the ocean.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 19,
    name: "Sarah Williams",
    location: "Chicago, USA",
    date: "May 22, 2025",
    image: "/beauty-skin.png",
    product: "Both Products",
    text: "The lotion cured my winter eczema! Combined with the scrub, my keratosis pilaris has improved dramatically. Finally found products that work with my sensitive skin.",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 20,
    name: "David Kim",
    location: "Seattle, USA",
    date: "April 18, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Radiance-Boosting Face Scrub",
    text: "Perfect for Asian skincare routines! The rice powder gives gentle exfoliation without irritation. I use it before sheet masks for better absorption. Better than my Korean imports!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 21,
    name: "Jennifer Martinez",
    location: "Austin, USA",
    date: "March 30, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Moisturizing & Soothing Body Lotion",
    text: "The rose scent is heavenly! I keep a bottle at my desk for hand moisturizing. Absorbs instantly so I can type right after. My coworkers keep asking what I'm using!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 22,
    name: "James Wilson",
    location: "Miami, USA",
    date: "June 25, 2025",
    image: "/beauty-skin.png",
    product: "Both Products",
    text: "As a Black man, finding non-greasy products is hard. This lotion moisturizes without clogging pores, and the scrub helps with ingrown hairs. Game changer for my grooming routine!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 23,
    name: "Amanda Thompson",
    location: "Denver, USA",
    date: "February 14, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Radiance-Boosting Face Scrub",
    text: "At 45, this gives me better results than chemical peels! The milk powder leaves my skin so soft. Perfect for high-altitude dryness. My esthetician asked what I changed in my routine!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 24,
    name: "Robert Chen",
    location: "San Francisco, USA",
    date: "May 5, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Moisturizing & Soothing Body Lotion",
    text: "Perfect for my minimalist lifestyle. One product replaces my separate day/night moisturizers. The olive oil gives deep hydration without breaking out my back. Vegan and effective!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 25,
    name: "Elizabeth Taylor",
    location: "Boston, USA",
    date: "April 10, 2025",
    image: "/beauty-skin.png",
    product: "Both Products",
    text: "Chemo left my skin so sensitive. These are the only products that don't irritate yet actually work! The lotion helps with radiation dryness and the scrub gently removes flaky skin. Bless whoever formulated these!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
  {
    id: 26,
    name: "Daniel Brown",
    location: "Portland, USA",
    date: "July 1, 2025",
    image: "/beauty-skin.png",
    product: "XYZ Radiance-Boosting Face Scrub",
    text: "As a barber, I recommend this to all my clients with beard dandruff. The natural ingredients don't irritate facial skin but effectively exfoliate. Makes shaves smoother too!",
    audioUrl: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    rating: 5,
  },
];

export const products = [
  {
    id: 1,
    name: "Luminous Glow Serum",
    category: "skincare",
    price: 68,
    description:
      "Vitamin C-rich serum with turmeric and licorice root for radiant complexion",
    imageSrc:
      "https://res.cloudinary.com/dnvjct2if/image/upload/v1752826641/Gemini_Generated_Image_sxmoodsxmoodsxmo_mgre4w.jpg",
    featured: false,
  },
  {
    id: 2,
    name: "Deep Hydration Cream",
    category: "skincare",
    price: 52,
    description: "Hyaluronic acid and aloe vera blend for intense moisture",
    imageSrc:
      "https://res.cloudinary.com/dnvjct2if/image/upload/v1752826837/Gemini_Generated_Image_jaqubnjaqubnjaqu_zv6xvo.jpg",
    featured: false,
  },
  {
    id: 3,
    name: "Herbal Infusion Toner",
    category: "skincare",
    price: 42,
    description: "Witch hazel and chamomile to balance and soothe skin",
    imageSrc:
      "https://res.cloudinary.com/dnvjct2if/image/upload/v1752826949/Gemini_Generated_Image_grkn42grkn42grkn_1_ghgdx2.jpg",
    featured: false,
  },
  {
    id: 4,
    name: "Radiant Skin Tint",
    category: "makeup",
    price: 48,
    description: "Lightweight tinted moisturizer with SPF 30 and adaptogens",
    imageSrc:
      "https://res.cloudinary.com/dnvjct2if/image/upload/v1752826033/Gemini_Generated_Image_iy257kiy257kiy25_z51l5t.jpg",
    featured: false,
  },
  {
    id: 5,
    name: "Volumizing Mascara",
    category: "makeup",
    price: 32,
    description: "Plant-based formula for lush, clump-free lashes",
    imageSrc:
      "https://res.cloudinary.com/dnvjct2if/image/upload/v1752826489/Gemini_Generated_Image_kk8oflkk8oflkk8o_cdz6jc.jpg",
    featured: true,
  },
  {
    id: 6,
    name: "Lip Nourish Balm",
    category: "makeup",
    price: 28,
    description: "Shea butter and rosehip oil for soft, hydrated lips",
    imageSrc:
      "https://res.cloudinary.com/dnvjct2if/image/upload/v1752826404/Gemini_Generated_Image_j9tnzgj9tnzgj9tn_pd1s2w.jpg",
    featured: true,
  },
  {
    id: 7,
    name: "Detox Clay Mask",
    category: "skincare",
    price: 58,
    description: "Bentonite clay and neem purify without stripping moisture",
    imageSrc:
      "https://res.cloudinary.com/dnvjct2if/image/upload/v1752826301/Gemini_Generated_Image_9kotpx9kotpx9kot_awgfbf.jpg",
    featured: true,
  },
  {
    id: 8,
    name: "Soothing Eye Cream",
    category: "skincare",
    price: 62,
    description: "Caffeine and cucumber reduce puffiness and dark circles",
    imageSrc:
      "https://res.cloudinary.com/dnvjct2if/image/upload/v1752826229/Gemini_Generated_Image_w01f8rw01f8rw01f_q11cwj.jpg",
    featured: false,
  },
];
